#! /bin/sh

# Desktop names
bspc monitor -d I II III IV V VI VII VIII IX X

# Config
bspc config border_width            2
bspc config window_gap              12
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config auto_alternate          true
bspc config auto_cancel             true

# Frames
bspc config focused_frame_opacity   0.1
bspc config active_frame_opacity    0
bspc config normal_frame_opacity    0

# Rules
bspc config rule_command "$(which bspwm_rules)"

# Panel
panel &
