#! /bin/sh

##  SETTINGS
bspc config border_width                0
bspc config window_gap                  40
bspc config top_padding                 19
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config auto_alternate              true
bspc config auto_cancel                 true

## DESKTOPS
bspc monitor -d 1 2 3 4 5 6 Web Games Music Graphics
bspc desktop Web -l monocole

## RULES
bspc rule -a Firefox desktop=Web
bspc rule -a Steam floating=true desktop=Games
bspc rule -a spotify desktop=Music
bspc rule -a Gimp floating=true desktop=Graphics
bspc rule -a URxvtFloating floating=true center=true
bspc rule -a feh floating=true center=true pseudo_tiled=true

## PANEL
$DOTFILES/WM/panel &
