#! /bin/sh

# Desktops
bspc monitor -d 1 2 3 4 5 Float 6 7 8 9 0
bspc desktop Float -t floating=on

# {{{ Settings

bspc config border_width                1
bspc config window_gap                  12
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config auto_alternate              true
bspc config auto_cancel                 true

# }}}
# {{{ Borders

# Focused
bspc config focused_border_color        "#606060"
bspc config active_border_color         "#606060"

# Default
bspc config normal_border_color         "#262626"
bspc config normal_locked_border_color  "#262626"
bspc config normal_sticky_border_color  "#262626"
bspc config normal_private_border_color "#262626"

# }}}
# {{{ Frames

bspc config focused_frame_opacity       0.2
bspc config active_frame_opacity        0
bspc config normal_frame_opacity        0

# }}}
# {{{ Rules

bspc rule -a BSPWM_FRAME frame=true
bspc rule -a Gimp floating=true
bspc rule -a Steam floating=true
bspc rule -a URxvtFloating floating=true center=true

# }}}

# Panel
$HOME/dotfiles/WM/dzen/panel &
