#!/bin/bash

# Init {{{

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# }}}
# Fifo {{{

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
exec 3<> "$PANEL_FIFO"

# }}}

# Updating {{{

bspc control --subscribe >"$PANEL_FIFO" &
xtitle -sf 'T%s' >"$PANEL_FIFO" &
while :; do echo "Time" >"$PANEL_FIFO"; sleep 3; done &

# }}}
# Printing {{{

tmux-sessions() {
    for i in $(seq 1 $(tmux list-sessions | wc -l)); do
        echo -n "• "
    done
}

while read -r line <"$PANEL_FIFO"; do
  case $line in
    N*) NOTIFY="${line#?}" ;;
    Time) TIME="%{F-} $(date +%H:%M)" ;;
    T*) TITLE="$(echo ${line#?} | cut -c -130)" ;;
    W*)
      # bspwm internal state
      NORMIFS=$IFS
      IFS=':'
      set -- ${line#?}
      desktops=""

      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}

        case $item in
          [OoFfUu]*)
            case $item in
              O*) # Focused ocupied desktop
                FG="%{F-}"
                [[ $name =~ [0-9]+ ]] && icon="•"
                ;;
              F*) # Focused free desktop
                FG="%{F-}"
                [[ $name =~ [0-9]+ ]] && icon="○"
                ;;
              o*) # Occupied desktop
                FG="%{F#ff0087af}"
                [[ $name =~ [0-9]+ ]] && icon="•"
                ;;
              f*) # Free desktop
                FG="%{F#ff444444}"
                [[ $name =~ [0-9]+ ]] && icon="○"
                ;;
              [uU]*) # Urgent desktop
                FG="%{F#ffaf8700}"
                [[ $name =~ [0-9]+ ]] && icon="•"
                ;;
            esac

            desktops+="%{A:bspc desktop -f $name:}$FG $icon%{A}%{F-} "
            ;;
        esac
        shift
      done
      IFS=$NORMIFS
      ;;
  esac

  echo "%{l}$TITLE %{c} $desktops %{r} $TIME $NOTIFY $(tmux-sessions)"
done | bar -f "-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*","-*-tewi-medium-*-*-*-11-*-*-*-*-*-*-*" -B "#00000000" -F "#ff9e9e9e" -u 2 -d -g 1880x16+20+5 |
    while read line; do eval "$line" ; done # Hande clickable area commands

# }}}

# vim: fdm=marker
