#! /bin/sh

##  SETTINGS
bspc config border_width                 1
bspc config window_gap                   12
bspc config top_padding                  28
bspc config bottom_padding               15
bspc config split_ratio                  0.5
bspc config borderless_monocle           true
bspc config focus_follows_pointer        true
bspc config pointer_follows_monitor      true
bspc config auto_alternate               true
bspc config auto_cancel                  true

bspc config normal_border_color          '#0a0f14'
bspc config focused_border_color         '#093748'
bspc config focused_sticky_border_color  '#4e5165'
bspc config focused_locked_border_color  '#edb54b'
bspc config focused_private_border_color '#33879d'

## DESKTOPS
bspc monitor --reset-desktops 1

## RULES
bspc rule -a spotify
bspc rule -a Gimp floating=true
bspc rule -a feh floating=true center=true pseudo_tiled=true
bspc rule -a skype floating=true

## PANEL
$DOTFILES/panel &
