# Xresources
xrdb -merge ~/.Xresources

# Fonts
xset +fp /usr/share/fonts/local
xset +fp ~/.fonts
xset fp rehash

# Key configurations
xmodmap ~/.Xmodmap
xcape

# Wallpaper: http://wallpapers.cc/wallpapers/10671
hsetroot -fill ~/Dropbox/Wallpapers/10671.jpg

# Mouse pointer
xsetroot -cursor_name left_ptr
unclutter -idle 2 &

compton &

# BSPWM
sxhkd &
exec bspwm
