#!/bin/bash

# Init {{{

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# }}}
# Fifo {{{

FIFO=/tmp/panel-fifo
[ -e "$FIFO" ] && rm "$FIFO"
mkfifo "$FIFO"
exec 3<> "$FIFO"

# }}}
# Functions {{{

Mail() { # {{{
  # $PASSWORD_STORE_DIR/Gmail/Dzen contains login:password
  email=$(curl -u $(cat $PASSWORD_STORE_DIR/Gmail/Dzen) --silent 'https://mail.google.com/mail/feed/atom' | grep fullcount | egrep -o '[0-9]+')

  (( email == 0 )) && return

  printf "%s" "%{F#ff444444}%{F-} $email"
}

# }}}
Pacman() { # {{{
  updates="$(pacmanupdates count)"

  (( updates == 0 )) && return

  printf "%s" "%{A:toggle-conky updates:}  $updates %{A}"
}

# }}}
Time() { #{{{
  printf "%s" "%{A:toggle-conky cal:}%{F-} $(date +%H:%M) %{A}"
}

# }}}
Volume() { #{{{
  vol=$(amixer get Master | egrep -o "[0-9]+%" | egrep -o "[0-9]*")
  mut=$(amixer get Master | egrep 'Playback.*?\[o' | egrep -o '\[o.+\]')

  color="%{F#ff606060}"
  icon=""

  if [[ "$mut" = "[off]" ]]; then
    icon=""
    color="%{F#ffaf0000}"
  elif (( vol < 25 )); then
    icon=""
  elif (( vol < 70 )); then
    icon=""
  fi

  printf "%s" "%{A:amixer set Master toggle:} $color$icon %{A}%{F-}$vol%% "

  for i in {0..10}; do
    percent="$(( i * 10 ))"
    if (( vol >= percent && vol != 0 )); then
      printf "%s" "%{A:amixer set Master $percent%%:}$color—%{A}%{F-}"
    else
      printf "%s" "%{F#ff303030}%{A:amixer set Master $percent%%:}—%{A}%{F-}"
    fi
  done
}

# }}}

# }}}

# Updating {{{

bspc control --subscribe >"$FIFO" &
xtitle -sf 'T%s' >"$FIFO" &
while :; do echo "S $(Volume) $(Time)" >"$FIFO"; sleep 3;   done &
while :; do echo "L $(Pacman) $(Mail)" >"$FIFO"; sleep 300; done &

# }}}
# Printing {{{

while read -r line <"$FIFO"; do
  case $line in
    L*) LONG="${line#?}" ;;
    S*) SHORT="${line#?}" ;;
    T*) TITLE="$(echo ${line#?} | cut -c -130)" ;;
    W*)
      # bspwm internal state
      NORMIFS=$IFS
      IFS=':'
      set -- ${line#?}
      desktops=()

      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        icon=$name

        case $item in
          [OoFfUu]*)
            case $item in
              O*) # Focused ocupied desktop
                FG="%{F-}"
                icon="•"
                ;;
              F*) # Focused free desktop
                FG="%{F-}"
                icon="○"
                ;;
              o*) # Occupied desktop
                FG="%{F#ff0087af}"
                icon="•"
                ;;
              f*) # Free desktop
                FG="%{F#ff444444}"
                icon="○"
                ;;
              [uU]*) # Urgent desktop
                FG="%{F#ffaf8700}"
                icon="•"
                ;;
            esac

            desktops+=("%{A:bspc desktop -f $name:}$FG $icon%{A}%{F-}")
            ;;
          L*)
            case $name in
              t*) LAYOUT="   %{F#ff0087af}%{F-}    " ;;
              m*) LAYOUT="   %{F#ff0087af}%{F-}    " ;;
            esac
            ;;
        esac
        shift
      done
      IFS=$NORMIFS
      DESK="${desktops[@]:0:5} $(Time) ${desktops[@]:5}"
      ;;
  esac

  echo "%{l}$LAYOUT$TITLE %{c} $DESK %{r} $LONG $SHORT"
done | bar -f "-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*","-*-tewi-medium-*-*-*-11-*-*-*-*-*-*-*" -B "#ff000000" -F "#ff9e9e9e" -u 2 -d |
    while read line; do eval "$line" ; done # Hande clickable area commands

# }}}

wait
