export EDITOR=vim

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export DOTFILES="$HOME/etc"
export PANEL_FIFO="/tmp/panel-fifo"

export ZDOTDIR="$DOTFILES/System/zsh"
export GNUPGHOME="$XDG_DATA_HOME/GnuPG"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/passwords-store"
export LESSHISTFILE="/dev/null"
export XAUTHORITY="$XDG_CACHE_HOME/Xauthority"
