export EDITOR=vim

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export DOTFILES="$HOME/dotfiles"
export ZDOTDIR="$DOTFILES/System/zsh"
export VIMINIT='let $MYVIMRC="$DOTFILES/Apps/vim/vimrc" | source $MYVIMRC'
