autoload -U colors && colors

# Remove dalay
KEYTIMEOUT=1

# Vi-Mode
bindkey -v

# Current mode
RPROMPT=""
function zle-line-init zle-keymap-select {
  RPROMPT="%{$fg[white]%} ${${KEYMAP/vicmd/«}/(main|viins)/} %{$reset_color%}"
  zle reset-prompt
  zle -R
}

zle -N zle-line-init
zle -N zle-keymap-select

# Prompt
PROMPT="
%{$fg[white]%} » %{$reset_color%}"

# More motions for vi-mode
source ~/dotfiles/System/zsh/opp/opp.zsh
source ~/dotfiles/System/zsh/opp/opp/*.zsh

# Window title
precmd() {
  print -Pn "\e]2;%100<...<%~%<<\a"
}

# Hitory
setopt append_history
setopt share_history
setopt hist_verify
setopt hist_ignore_all_dups
export HISTFILE="$HOME/.zsh-history"
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE

setopt AUTO_CD
setopt CORRECT
