autoload -U colors && colors

# Remove dalay
KEYTIMEOUT=1

# {{{ Vi-Mode

bindkey -v

# Current mode
RPROMPT=""
function zle-line-init zle-keymap-select {
  RPROMPT="%{$fg[white]%} ${${KEYMAP/vicmd/«}/(main|viins)/} %{$reset_color%}"
  zle reset-prompt
  zle -R
}

zle -N zle-line-init
zle -N zle-keymap-select

# More motions
source ~/dotfiles/System/zsh/opp/opp.zsh
source ~/dotfiles/System/zsh/opp/opp/*.zsh

# }}}
# {{{ Hitory

setopt append_history
setopt share_history
setopt hist_verify
setopt hist_ignore_all_dups
export HISTFILE="$HOME/.zsh-history"
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE

# }}}

# Prompt
PROMPT="
%{$fg[white]%} » %{$reset_color%}"

# Window title
precmd() {
  print -Pn "\e]2;%100<...<%~%<<\a"
}


setopt AUTO_CD
setopt CORRECT

# Aliases
alias ls='ls --color=auto'
