# Xresources
xrdb -merge ~/.Xresources

# # terminus font
# xset +fp ~/.fonts/terminus
# xset fp rehash

# Key configurations
xmodmap ~/.Xmodmap
xcape

# Wallpaper
hsetroot -fill ~/Dropbox/Wallpapers/a.png

# Mouse pointer
xsetroot -cursor_name left_ptr
unclutter -idle 2 &

compton &

# BSPWM
sxhkd &
exec bspwm
