# Remove dalay
KEYTIMEOUT=1

# Vi-Mode
bindkey -v

# Current mode
RPROMPT=""
function zle-line-init zle-keymap-select {
  VIMODE="${${KEYMAP/vicmd/Command}/(main|viins)/Insert}"
  RPROMPT="$VIMODE"
  zle reset-prompt
  zle -R
}

zle -N zle-line-init
zle -N zle-keymap-select

# Prompt
PROMPT="
%{$fg[white]%} » %{$reset_color%}"

source ~/GitRepos/opp.zsh/opp.zsh
source ~/GitRepos/opp.zsh/opp/*.zsh

# Window title
precmd() {
  print -Pn "\e]2;%100<...<%~%<<\a"
}

# Hitory
setopt append_history
setopt share_history
setopt hist_verify
setopt hist_ignore_all_dups
export HISTFILE="$HOME/.zsh-history"
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE
