#!/bin/bash

# Init {{{

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# }}}
# Fifo {{{

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
exec 3<> "$PANEL_FIFO"

# }}}
# Functions {{{

Pacman() { # {{{
  updates="$(pacmanupdates count)"

  (( updates == 0 )) && return

  printf "%s" " $updates"
}

# }}}
Time() { #{{{
  printf "%s" "%{F-} $(date +%H:%M)"
}

# }}}

# }}}

# Updating {{{

bspc control --subscribe >"$PANEL_FIFO" &
xtitle -sf 'T%s' >"$PANEL_FIFO" &
while :; do echo "I $(Pacman)" >"$PANEL_FIFO"; sleep 300; done &

# }}}
# Printing {{{

notifyStop=-1

while read -r line <"$PANEL_FIFO"; do
  case $line in
    I*) INFO="${line#?}" ;;
    N*) NOTIFY="${line#?}" ;;
    T*) TITLE="$(echo ${line#?} | cut -c -130)" ;;
    W*)
      # bspwm internal state
      NORMIFS=$IFS
      IFS=':'
      set -- ${line#?}
      desktops=()

      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        icon=$name

        case $item in
          [OoFfUu]*)
            case $item in
              O*) # Focused ocupied desktop
                FG="%{F-}"
                icon="•"
                ;;
              F*) # Focused free desktop
                FG="%{F-}"
                icon="○"
                ;;
              o*) # Occupied desktop
                FG="%{F#ff0087af}"
                icon="•"
                ;;
              f*) # Free desktop
                FG="%{F#ff444444}"
                icon="○"
                ;;
              [uU]*) # Urgent desktop
                FG="%{F#ffaf8700}"
                icon="•"
                ;;
            esac

            desktops+=("%{A:bspc desktop -f $name:}$FG $icon%{A}%{F-}")
            ;;
        esac
        shift
      done
      IFS=$NORMIFS
      ;;
  esac

  echo "%{l}$TITLE %{c} ${desktops[@]:0:5} $(Time) ${desktops[@]:5} %{r} $INFO $NOTIFY"
done | bar -f "-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*","-*-tewi-medium-*-*-*-11-*-*-*-*-*-*-*" -B "#00000000" -F "#ff9e9e9e" -u 2 -d -g 1880x16+20+5 |
    while read line; do eval "$line" ; done # Hande clickable area commands

# }}}

wait

# vim: fdm=marker
