#!/bin/bash

# Init {{{

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# }}}
# Fifo {{{

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
exec 3<> "$PANEL_FIFO"

# }}}
# Functions {{{

Mail() { # {{{
  # $PASSWORD_STORE_DIR/Gmail/Dzen contains login:password
  email=$(curl -u $(cat $PASSWORD_STORE_DIR/Gmail/Dzen) --silent 'https://mail.google.com/mail/feed/atom' | grep fullcount | egrep -o '[0-9]+')

  (( email == 0 )) && return
  (( email == 1 )) && s='' || s='s'

  printf "%s" "%{F#ff444444}%{F-} $email"

  notify-send "You have $email unread message$s!"
}

# }}}
Pacman() { # {{{
  updates="$(pacmanupdates count)"

  (( updates == 0 )) && return

  printf "%s" " $updates"

  info="There are $updates updates available!"
  (( updates == 1 )) && info="There is 1 update available!"

  notify-send "$info" "$(pacmanupdates list | sed 's/^/ • /')"
}

# }}}
Time() { #{{{
  printf "%s" "%{F-} $(date +%H:%M)"
}

# }}}

# }}}

# Updating {{{

bspc control --subscribe >"$PANEL_FIFO" &
xtitle -sf 'T%s' >"$PANEL_FIFO" &
while :; do echo "I $(Pacman) $(Mail)" >"$PANEL_FIFO"; sleep 300; done &

# }}}
# Printing {{{

notifyStop=-1

while read -r line <"$PANEL_FIFO"; do
  case $line in
    I*) INFO="${line#?}" ;;
    N*) NOTIFY="${line#?}" ;;
    T*) TITLE="$(echo ${line#?} | cut -c -130)" ;;
    W*)
      # bspwm internal state
      NORMIFS=$IFS
      IFS=':'
      set -- ${line#?}
      desktops=()

      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        icon=$name

        case $item in
          [OoFfUu]*)
            case $item in
              O*) # Focused ocupied desktop
                FG="%{F-}"
                icon="•"
                ;;
              F*) # Focused free desktop
                FG="%{F-}"
                icon="○"
                ;;
              o*) # Occupied desktop
                FG="%{F#ff0087af}"
                icon="•"
                ;;
              f*) # Free desktop
                FG="%{F#ff444444}"
                icon="○"
                ;;
              [uU]*) # Urgent desktop
                FG="%{F#ffaf8700}"
                icon="•"
                ;;
            esac

            desktops+=("%{A:bspc desktop -f $name:}$FG $icon%{A}%{F-}")
            ;;
          L*)
            case $name in
              t*) LAYOUT="   %{F#ff0087af}%{F-}    " ;;
              m*) LAYOUT="   %{F#ff0087af}%{F-}    " ;;
            esac
            ;;
        esac
        shift
      done
      IFS=$NORMIFS
      ;;
  esac

  echo "%{l}$LAYOUT$TITLE %{c} ${desktops[@]:0:5} $(Time) ${desktops[@]:5} %{r} $INFO $NOTIFY"
done | bar -f "-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*","-*-tewi-medium-*-*-*-11-*-*-*-*-*-*-*" -B "#88000000" -F "#ff9e9e9e" -u 2 -d |
    while read line; do eval "$line" ; done # Hande clickable area commands

# }}}

wait
