#!/bin/bash

# Init {{{


if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

. $(dirname $0)/common.sh


# }}}
# Fifo {{{


FIFO=/tmp/panel-fifo
[ -e "$FIFO" ] && rm "$FIFO"
mkfifo "$FIFO"
exec 3<> "$FIFO"


# }}}
# Variables {{{


NORMIFS=$IFS
FIELDIFS=':'

PANEL_HEIGHT=15
EVENTS=''

bspc config top_padding $PANEL_HEIGHT


# }}}
# Functions {{{

Time() { #{{{
  printf "^ca(1,$(Script date.sh))%s^ca()" "$(Icon clock '#444444') $(date +%H:%M:%S)"
}

# }}}
Volume() { #{{{
  vol=$(amixer get Master | egrep -o "[0-9]+%" | egrep -o "[0-9]*")
  mut=$(amixer get Master | egrep 'Playback.*?\[o' | egrep -o '\[o.+\]')

  if [[ $vol -eq 0 ]]; then
    ico="$(Icon volume0 '#444444')"
  elif [[ $vol -eq 100 ]]; then
    ico="$(Icon volume100 '#444444')"
  elif [[ $vol -lt 100 && $vol -gt 60 ]]; then
    ico="$(Icon volume75 '#444444')"
  elif [[ $vol -le 60 && $vol -gt 30 ]]; then
    ico="$(Icon volume50 '#444444')"
  elif [[ $vol -le 30 && $vol -gt 0 ]]; then
    ico="$(Icon volume25 '#444444')"
  fi

  [ "$mut" = "[off]" ] && ico="$(Icon volume0 '#444444')"

  printf "^ca(1,$(Script volume.sh)) $ico ^ca()"
}

# }}}
Menu() { # {{{
  printf "^ca(1,$(Script menu.sh)) $(Icon arch '#0087af')  ^ca()"
}

# }}}
Pacman() {
  updates=$(pacman -Qu | wc -l)

  if [[ $updates -gt 99 ]]; then
    updates="99+" # That shouldn't happen but...
  elif [[ $updates -eq 0 ]]; then
    return
  fi
  
  printf "^ca(1,$(Script pacman.sh)) $(Icon pacman '#444444') $updates ^ca()"
}

# }}}

# Updating {{{


bspc control --subscribe >&3 &
xtitle -sf 'T%s' >&3 &
while :; do
  echo "S$(Time)" >&3
  sleep 3
done &


# }}}
# Printing {{{

while read -r line <&3; do
  case $line in
    S*)
      TIME="$(Align right -190; Pacman; Align right -140; Volume) ${line#?}"
      ;;
    T*)
      TITLE="${line#?}"
      ;;
    W*)
      # bspwm internal state
      DESK=" $(Align center -147) "
      IFS=$FIELDIFS
      set -- ${line#?}

      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        icon=$name

        case $item in
          [OoFfUu]*)
            case $item in
              O*) # Focused ocupied desktop
                FG='#9e9e9e'
                [[ "$name" = [0-9] ]] && icon=" •"
                ;;
              F*) # Focused free desktop
                FG='#9e9e9e'
                [[ "$name" = [0-9] ]] && icon=" ○"
                ;;
              o*) # Occupied desktop
                FG='#0087af'
                [[ "$name" = [0-9] ]] && icon=" •"
                ;;
              f*) # Free desktop
                FG='#444444'
                [[ "$name" = [0-9] ]] && icon=" ○"
                ;;
              [uU]*) # Urgent desktop
                FG='#af8700'
                [[ "$name" = [0-9] ]] && icon=" •"
                ;;
            esac

            DESK="${DESK}^fg($FG)^ca(1, bspc desktop -f ${name})^ca(2, bspc window -d ${name}) ${icon} ^ca()^ca()^fg()"
            ;;
        esac
        shift
      done
      IFS=$NORMIFS
      ;;
  esac

  echo "$(Align left; Menu) $TITLE $DESK $TIME"
done | dzen2 -h "$PANEL_HEIGHT" -ta l -e "$EVENTS" &

# }}}

wait
