#! /bin/bash

# Variables {{{

NORMIFS=$IFS
FIELDIFS=':'

# }}}
# Functions {{{

Align() { #{{{
  case $1 in
    left)   printf "^p(_LEFT)"    ;;
    center) printf "^p(_CENTER)"  ;;
    right)  printf "^p(_RIGHT)"   ;;
  esac

  [ -n $2 ] && printf "^p($2)"
}

# }}}
Separate() { #{{{
  printf "     "
}

# }}}
Icon() { #{{{
  printf "^fg(#505050) ^i(%s) ^fg()" "$HOME/dotfiles/WM/dzen/icons/${1}.xbm"
}

# }}}
Script() { # {{{
  printf "pkill $1 || $HOME/dotfiles/WM/dzen/$1"
}

# }}}

Desks() { #{{{
  read -r -t .1 line

  case "$line" in
    W*)
      # bspwm internal state
      DESK="  "
      IFS=$FIELDIFS
      set -- ${line#?}

      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        icon=" • "

        case $item in
          [OoFfUu]*)
            case $item in
              [OFU]*) # Focused desktop
                FG='#ffffff'
                BG='#262626'
                ;;

              o*) # Occupied desktop
                FG='#5e6c70'
                BG='#262626'
                ;;

              f*) # Free desktop
                FG='#000000'
                BG='#262626'
                ;;

              u*) # Urgent desktop
                FG='#000000'
                BG='#262626'
                ;;
            esac

            DESK="${DESK}^fg($FG)^bg($BG)^ca(1, bspc desktop -f ${name})^ca(2, bspc window -d ${name}) ${icon} ^ca()^ca()^fg()^bg()"
            ;;
        esac
        shift
      done
      IFS=$NORMIFS
      ;;
  esac

  printf "$DESK"
}

# }}}
Time() { #{{{
  printf "%s" "$(Icon clock) $(date +%H:%M:%S)"
}

# }}}
Title() { #{{{
  printf " %s " "$(xtitle)"
}

# }}}
Volume() { #{{{
  vol=$(amixer get Master | egrep -o "[0-9]+%" | egrep -o "[0-9]*")
  mut=$(amixer get Master | egrep 'Playback.*?\[o' | egrep -o '\[o.+\]')

  if [ $vol -eq 0 ]; then
    ico="$(Icon volume0)"
  elif [ $vol -eq 100 ]; then
    ico="$(Icon volume100)"
  elif [ $vol -lt 100 ] && [ $vol -gt 60 ]; then
    ico="$(Icon volume75)"
  elif [ $vol -le 60 ] && [ $vol -gt 30 ]; then
    ico="$(Icon volume50)"
  elif [ $vol -le 30 ] && [ $vol -gt 0 ]; then
    ico="$(Icon volume25)"
  fi

  [ "$mut" = "[off]" ] && ico="$(Icon volume0)"

  printf "^ca(1,$(Script volume.sh)) $ico ^ca()"
}

# }}}

Menu() { # {{{
  printf "^ca(1,$(Script menu.sh)) M  ^ca()"
}

# }}}

# }}}

while :; do
  Align left
  Menu
  Title

  Align center -130
  Desks

  Align right -140
  Volume

  Separate
  Time
  echo
done

