#! /bin/sh

# Init {{{

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# }}}
# Fifo {{{

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &

# }}}
# Variables {{{

PANEL_HEIGHT=18
EVENTS=''

# }}}

bspc config top_padding $PANEL_HEIGHT

cat "$PANEL_FIFO" | $HOME/dotfiles/WM/dzen/panel_dzen2 | dzen2 -h "$PANEL_HEIGHT" -ta 'l' -e "$EVENTS" &

wait
