#!/bin/bash
updates="$(checkupdates)"
if [[ -n "$updates" ]]; then
  count=$(echo "$updates" | wc -l)
else
  count=0
fi

action="${1:-count}"

case $action in
  count)
    echo "$count"
    ;;
  list)
    echo "$updates"
    ;;
esac
