#! /bin/sh

# Init {{{

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# }}}
# Fifo {{{

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &

# }}}
# Variables {{{

PANEL_HEIGHT=15
FONT='DejaVu Sans'
FONT_SIZE=11
FG='#9e9e9e'
BG='#262626'
EVENTS='"button3=;"'

# }}}

bspc config top_padding $PANEL_HEIGHT

cat "$PANEL_FIFO" | panel_dzen2 | dzen2 -h "$PANEL_HEIGHT" -fg "$FG" -bg "$BG" -fn "${FONT}:pixelsize=$FONT_SIZE" -ta 'l' -e "$EVENTS" &

wait
