#! /bin/bash

# Variables {{{

NORMIFS=$IFS
FIELDIFS=':'

# }}}
# Functions {{{

Icon() { #{{{
  printf "^fg(#505050) ^i(%s) ^fg()" "$HOME/dotfiles/WM/icons/${1}.xbm"
} #}}}

Time() { #{{{
  printf "^p(_RIGHT)^p(-80)%s" "$(Icon clock) $(date +%H:%M:%S)"
} #}}}

Title() { #{{{
  printf "^p(_LEFT)%s ^p()" "$(xtitle)"
} #}}}

Desks() { #{{{
  read -r -t .1 line

  case "$line" in
    W*)
      # bspwm internal state
      DESK="  "
      IFS=$FIELDIFS
      set -- ${line#?}

      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        icon=" • "

        case $item in
          [OoFfUu]*)
            case $item in
              [OFU]*) # Focused desktop
                FG='#ffffff'
                BG='#262626'
                ;;

              o*) # Occupied desktop
                FG='#5e6c70'
                BG='#262626'
                ;;

              f*) # Free desktop
                FG='#000000'
                BG='#262626'
                ;;

              u*) # Urgent desktop
                FG='#000000'
                BG='#262626'
                ;;
            esac

            DESK="${DESK}^fg($FG)^bg($BG)^ca(1, bspc desktop -f ${name})^ca(2, bspc window -d ${name}) ${icon} ^ca()^ca()^fg()^bg()"
            ;;
        esac
        shift
      done
      IFS=$NORMIFS
      ;;
  esac

  printf "^p(_CENTER)^p(-130)$DESK^p()"
} #}}}

# }}}

while :; do
  Title
  Desks
  Time
  echo
done
